<!-- Content -->

<div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
            <!-- Register -->
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-2">Gerenciamento de Conteúdo</h4>

                    <form id="formAuthentication" class="mb-3" action="/auth" method="POST">
                        <div class="mb-3">
                            <label for="usuario" class="form-label">Nome de Usuário</label>
                            <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Nome de Usuário" autofocus required />
                        </div>
                        <div class="mb-3 form-password-toggle">
                            <div class="d-flex justify-content-between">
                                <label class="form-label" for="password">Senha</label>
                            </div>
                            <div class="mb-3">
                                <input type="password" class="form-control" id="senha" name="senha" placeholder="Senha" required />
                            </div>
                        </div>
                        <div class="mb-3">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="remember-me" />
                                <label class="form-check-label" for="remember-me"> Lembrar de mim </label>
                            </div>
                        </div>
                        <div class="mb-3">
                            <button class="btn btn-success w-100" type="submit">Iniciar Sessão</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /Register -->
        </div>
    </div>
</div>

<!-- / Content -->