<!-- Content -->

<div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-2 text-center mb-5">Reculperação de Senha</h4>
                    <form id="formAuthentication" class="mb-3" action="/recoverypwd" method="POST">
                        <div class="mb-3">
                            <label for="usuario" class="form-label">E-mail</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="E-mail de usuário" required />
                        </div>
                        <div class="mb-3">
                            <button class="btn btn-success w-100" type="submit">Enviar Link</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- / Content -->