<main>
    <section class="hero-section hero-section-full-height" id="inicio">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 col-12 p-0">
                    <div id="hero-slide" class="carousel carousel-fade slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="images/slide/volunteer-helping-with-donation-box.jpg" class="carousel-image img-fluid" alt="...">

                                <div class="carousel-caption d-flex flex-column justify-content-end">
                                    <h1>Depilação</h1>

                                    <p>Depilação com cera negra</p>

                                </div>
                            </div>

                            <!-- <div class="carousel-item">
                                <img src="images/slide/volunteer-selecting-organizing-clothes-donations-charity.jpg" class="carousel-image img-fluid" alt="...">

                                <div class="carousel-caption d-flex flex-column justify-content-end">
                                    <h1>Estética</h1>

                                    <p>You can support us to grow more</p>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <img src="images/slide/medium-shot-people-collecting-donations.jpg" class="carousel-image img-fluid" alt="...">

                                <div class="carousel-caption d-flex flex-column justify-content-end">
                                    <h1>Hamonização</h1>

                                    <p>Please tell your friends about our website</p>
                                </div>
                            </div> -->
                        </div>

                        <button class="carousel-control-prev" type="button" data-bs-target="#hero-slide" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>

                        <button class="carousel-control-next" type="button" data-bs-target="#hero-slide" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <section class="section-padding" id="servicos">
        <div class="container">
            <div class="row">

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <h2 class="mb-5">Nossos Serviços</h2>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="featured-block d-flex justify-content-center align-items-center">
                        <a class="d-block" data-bs-toggle="modal" data-bs-target="#modalserviços">
                            <img src="images/icons/hands.png" class="featured-block-image img-fluid" alt="">

                            <p class="featured-block-text">Become a <strong>volunteer</strong></p>
                        </a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0 mb-md-4">
                    <div class="featured-block d-flex justify-content-center align-items-center">
                        <a class="d-block" data-bs-toggle="modal" data-bs-target="#modalserviços">
                            <img src="images/icons/heart.png" class="featured-block-image img-fluid" alt="">

                            <p class="featured-block-text"><strong>Caring</strong> Earth</p>
                        </a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0 mb-md-4">
                    <div class="featured-block d-flex justify-content-center align-items-center">
                        <a class="d-block" data-bs-toggle="modal" data-bs-target="#modalserviços">
                            <img src="images/icons/receive.png" class="featured-block-image img-fluid" alt="">

                            <p class="featured-block-text">Make a <strong>Donation</strong></p>
                        </a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="featured-block d-flex justify-content-center align-items-center">
                        <a class="d-block" data-bs-toggle="modal" data-bs-target="#modalserviços">
                            <img src="images/icons/scholarship.png" class="featured-block-image img-fluid" alt="">

                            <p class="featured-block-text"><strong>Scholarship</strong> Program</p>
                        </a>
                    </div>
                </div>

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" href="">Agende Agora
                    </a>
                </div>

            </div>
        </div>
    </section>

    <section class="testimonial-section section-padding section-bg" id="avaliacoes">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 col-12 mx-auto">
                    <h2 class="mb-lg-3">Avaliações de nossos clientes</h2>

                    <div id="testimonial-carousel" class="carousel carousel-fade slide" data-bs-ride="carousel">

                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <div class="carousel-caption">
                                    <h4 class="carousel-title">Lorem Ipsum dolor sit amet, consectetur adipsicing
                                        kengan omeg kohm tokito charity theme</h4>

                                    <small class="carousel-name"><span class="carousel-name-title">Maria</span>,
                                        Boss</small>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <div class="carousel-caption">
                                    <h4 class="carousel-title">Sed leo nisl, posuere at molestie ac, suscipit auctor
                                        mauris quis metus tempor orci</h4>

                                    <small class="carousel-name"><span class="carousel-name-title">Thomas</span>,
                                        Partner</small>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <div class="carousel-caption">
                                    <h4 class="carousel-title">Lorem Ipsum dolor sit amet, consectetur adipsicing
                                        kengan omeg kohm tokito charity theme</h4>

                                    <small class="carousel-name"><span class="carousel-name-title">Jane</span>,
                                        Advisor</small>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <div class="carousel-caption">
                                    <h4 class="carousel-title">Sed leo nisl, posuere at molestie ac, suscipit auctor
                                        mauris quis metus tempor orci</h4>

                                    <small class="carousel-name"><span class="carousel-name-title">Bob</span>,
                                        Entreprenuer</small>
                                </div>
                            </div>

                            <ol class="carousel-indicators">
                                <li data-bs-target="#testimonial-carousel" data-bs-slide-to="0" class="active">
                                    <img src="images/avatar/portrait-beautiful-young-woman-standing-grey-wall.jpg" class="img-fluid rounded-circle avatar-image" alt="avatar">
                                </li>

                                <li data-bs-target="#testimonial-carousel" data-bs-slide-to="1" class="">
                                    <img src="images/avatar/portrait-young-redhead-bearded-male.jpg" class="img-fluid rounded-circle avatar-image" alt="avatar">
                                </li>

                                <li data-bs-target="#testimonial-carousel" data-bs-slide-to="2" class="">
                                    <img src="images/avatar/pretty-blonde-woman-wearing-white-t-shirt.jpg" class="img-fluid rounded-circle avatar-image" alt="avatar">
                                </li>

                                <li data-bs-target="#testimonial-carousel" data-bs-slide-to="3" class="">
                                    <img src="images/avatar/studio-portrait-emotional-happy-funny.jpg" class="img-fluid rounded-circle avatar-image" alt="avatar">
                                </li>
                            </ol>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <section class="section-padding" id="sobrenos">
        <div class="container">
            <div class="row">

                <div class="col-lg-12 col-12">
                    <div class="col-lg-10 col-12 text-center mx-auto">
                        <h2 class="mb-5">Sobre a Art Corpus</h2>
                    </div>
                    <div class="custom-text-box">

                        <p class="mb-0">This is a Bootstrap 5.2.2 CSS template for charity organization websites.
                            You can feel free to use it. Please tell your friends about TemplateMo website. Thank
                            you.
                        </p>
                    </div>
                </div>

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" href="">Venha nos conhecer
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal de serviços -->
    <div class="modal fade" id="modalserviços" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalserviçosLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Sed leo nisl, posuere at molestie ac, suscipit auctor mauris quis metus tempor orci</p>
                </div>
                <div class="modal-footer ">
                    <a class="custom-btn btn text-center mx-auto" href="">
                        <i class="bi-whatsapp" style="padding-right: 1px;"></i>WhatsApp
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Fim modal de serviços -->
</main>