<main>
    <section class="hero-section hero-section-full-height" id="inicio">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 col-12 p-0">
                    <div id="hero-slide" class="carousel carousel-fade slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <?php foreach ($this->view->slide as $key => $slide) : ?>
                                <div class="carousel-item <?= $key == 0 ? 'active' : '' ?> ">
                                    <img src="storage/slides/<?= $slide['imagem'] ?>" class="carousel-image img-fluid" alt="...">

                                    <div class="carousel-caption d-flex flex-column justify-content-end">
                                        <h1><?= $slide['titulo'] ?></h1>
                                        <p><?= $slide['descricao'] ?></p>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php
                                if (isset($this->view->slide)) {
                                    echo '
                                        <button class="carousel-control-prev" type="button" data-bs-target="#hero-slide" data-bs-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="visually-hidden">Previous</span>
                                        </button>
                                        <button class="carousel-control-next" type="button" data-bs-target="#hero-slide" data-bs-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="visually-hidden">Next</span>
                                        </button>';
                                } else {
                                    echo '';
                                }
                            ?>
                        </div>
                    </div>

                </div>
            </div>
    </section>

    <section class="section-padding" id="servicos">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-12 text-center mx-auto">
                    <h2 class="mb-5">Nossos Serviços</h2>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="featured-block d-flex justify-content-center align-items-center">
                        <a class="d-block" data-bs-toggle="modal" data-bs-target="#modalservicos">
                            <img src="images/icons/hands.png" class="featured-block-image img-fluid" alt="">

                            <p class="featured-block-text">Become a <strong>volunteer</strong></p>
                        </a>
                    </div>
                </div>

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" href="">Agende Agora
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="testimonial-section section-padding section-bg" id="perguntas" style="padding-top: 100px;">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 col-12 mx-auto text-center">
                    <h2 class="mb-lg-3">Dúvidas Frequentes</h2>
                    <small>Alguma das dúvidas frequentes de nossas clientes.</small>
                    <div id="testimonial-carousel">

                        <div class="accordion m-5" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        Titulo da dúvida
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingTwo">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        Titulo da dúvida
                                    </button>
                                </h2>
                                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingThree">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                        Titulo da dúvida
                                    </button>
                                </h2>
                                <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <section class="section-padding" id="sobrenos">
        <div class="container">
            <div class="row">

                <div class="col-lg-12 col-12">
                    <div class="col-lg-10 col-12 text-center mx-auto">
                        <h2 class="mb-5">Sobre a Art Corpus</h2>
                    </div>
                    <div class="custom-text-box">

                        <p class="mb-0">This is a Bootstrap 5.2.2 CSS template for charity organization websites.
                            You can feel free to use it. Please tell your friends about TemplateMo website. Thank
                            you.
                        </p>
                    </div>
                </div>

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" href="">Venha nos conhecer
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal de serviços -->
    <div class="modal fade" id="modalservicos" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalservicosLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Titulo do serviço</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
                </div>
                <div class="modal-footer">
                    <a class="custom-btn btn text-center mx-auto" href="">
                        <i class="bi-whatsapp" style="padding-right: 2px;"></i>Agende pelo WhatsApp
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Fim modal de serviços -->
</main>