<main>
    <section class="hero-section hero-section-full-height" id="inicio">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12 col-12 p-0">
                    <div id="hero-slide" class="carousel carousel-fade slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <?php foreach ($this->view->slide as $key => $slide) : ?>
                                <div class="carousel-item <?= $key == 0 ? 'active' : '' ?> ">
                                    <img src="storage/slides/<?= $slide['imagem'] ?>" class="carousel-image img-fluid" alt="...">

                                    <div class="carousel-caption d-flex flex-column justify-content-end">
                                        <h1><?= $slide['titulo'] ?></h1>
                                        <p><?= $slide['descricao'] ?></p>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php
                            if (isset($this->view->slide)) {
                                echo '
                                        <button class="carousel-control-prev" type="button" data-bs-target="#hero-slide" data-bs-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="visually-hidden">Previous</span>
                                        </button>
                                        <button class="carousel-control-next" type="button" data-bs-target="#hero-slide" data-bs-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="visually-hidden">Next</span>
                                        </button>';
                            } else {
                                echo '';
                            }
                            ?>
                        </div>
                    </div>

                </div>
            </div>
    </section>

    <section class="section-padding" id="servicos">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-12 text-center mx-auto">
                    <h2 class="mb-5">Nossos Serviços</h2>
                </div>

                <?php foreach ($this->view->servico as $key => $servico) : ?>
                    <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                        <div class="featured-block d-flex justify-content-center align-items-center">
                            <a class="d-block" data-bs-toggle="modal" data-bs-target="#modalservicos<?= $servico['id'] ?>">
                                <img src="storage/servicos/<?= $servico['imagem'] ?>" class="featured-block-image img-fluid" alt="servicoImagem">

                                <p class="featured-block-text"><?= $servico['nome'] ?></p>
                            </a>
                        </div>
                    </div>
                    <!-- Modal de serviços -->
                    <!-- <div class="modal fade" id="modalservicos<?= $servico['id'] ?>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalservicosLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel"><?= $servico['nome'] ?></h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p><?= $servico['descricao'] ?></p>
                                </div>
                                <div class="modal-footer">
                                    <a class="custom-btn btn text-center mx-auto" href="https://wa.me/<?= $this->view->contato['whatsapp'] ?>">
                                        <i class="bi-whatsapp" style="padding-right: 2px;"></i>Agende pelo WhatsApp
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <!-- Fim modal de serviços -->
                <?php endforeach ?>

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" href="https://wa.me/<?= $this->view->contato['whatsapp'] ?>" target="__blank">Agende Agora
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="testimonial-section section-padding section-bg" id="perguntas" style="padding-top: 100px;">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 col-12 mx-auto text-center">
                    <h2 class="mb-lg-3">Dúvidas Frequentes</h2>
                    <small>Alguma das dúvidas frequentes de nossas clientes.</small>
                    <div id="testimonial-carousel">

                        <div class="accordion m-5" id="accordionDuvida">
                            <?php foreach ($this->view->duvida as $key => $duvida) { ?>
                                <div class="card accordion-item" style="margin-bottom: 1%;">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button type="button" class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#<?= 'duvida' . $duvida['id'] ?>" aria-expanded="false" aria-controls="<?= 'duvida' . $duvida['id'] ?>">
                                            <?= $duvida['titulo'] ?>
                                        </button>
                                    </h2>

                                    <div id="<?= 'duvida' . $duvida['id'] ?>" class="accordion-collapse collapse" data-bs-parent="#accordionDuvida">
                                        <div class="accordion-body">
                                            <strong>Resposta:</strong> <?= $duvida['duvida'] ?><br>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" target="__blank" href="<?= $this->view->contato['localizacao'] ?>">Venha nos conhecer
                    </a>
                </div>                     
            </div>
        </div>
    </section>

    <section class="section-padding" id="sobrenos" style="padding-top: 100px;">
        <div class="container">
            <div class="row">

                <div class="col-lg-12 col-12">
                    <div class="col-lg-10 col-12 text-center mx-auto">
                        <h2 class="mb-5">Sobre a Art Corpus</h2>
                    </div>
                    <div class="custom-text-box text-center">

                        <p class="mb-0">
                            <?= $this->view->contato['sobre'] ?>
                        </p>
                    </div>
                </div>

                <div class="col-lg-10 col-12 text-center mx-auto">
                    <a class="custom-btn btn mt-3" target="__blank" href="<?= $this->view->contato['localizacao'] ?>">Venha nos conhecer
                    </a>
                </div>
            </div>
        </div>
    </section>

</main>