<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Formulário/</span> Criação de Usuário</h4>

    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Dados do usuário</h5>
                    <small class="float-end" style="color: red;">Todos os campos são obrigatórios</small>
                </div>
                <div class="card-body">
                    <form method="post" action="/storeuser" enctype="multipart/form-data">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="nome-completo">Nome Completo</span>
                            <input type="text" class="form-control" placeholder="Nome Completo" aria-label="Nome Completo" aria-describedby="nome-completo" name="nome" required>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon11">Nome de Usuário</span>
                            <input type="text" class="form-control" placeholder="Usuário" aria-label="Usuário" name="usuario" required>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon11">E-mail</span>
                            <input type="email" class="form-control" placeholder="Endereço de E-mail" aria-label="E-mail" name="email" required>
                        </div>

                        <small>Requisitor para a Senha</small>
                        <ul>
                            <li>Minimo 8 Caracteres</li>
                            <li>Letras e Números</li>
                        </ul>
                        <div class="form-password-toggle">
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="passwordcampo">Senha</span>
                                <input type="password" class="form-control" id="basic-default-password12" placeholder="············" aria-describedby="passwordcampo" minlength="8" required>
                                <span id="basic-default-password2" class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                            </div>
                        </div>

                        <div class="input-group mb-3">
                            <label class="input-group-text" for="inputGroupFile01">Foto de Perfil</label>
                            <input type="file" class="form-control" id="inputGroupFile01" name="imagem" required>
                        </div>
                        <button type="submit" class="btn btn-success">Salvar dados</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>