<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Lista /</span> Todos os usuários</h4>

    <!-- Basic Bootstrap Table -->
    <div class="card">
        <h5 class="card-header">Dados dos Usuários</h5>
        <div class="table-responsive text-nowrap">
            <table class="table text-center justify-content-center">
                <thead>
                    <tr>
                        <th>Foto de Perfil</th>
                        <th>Nome</th>
                        <th>Usuário</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <?php foreach ($this->view->usuarios as $indice => $usuario) { ?>
                    <tbody class="table-border-bottom-0">
                        <tr>
                            <td class="text-center">
                                <ul class="list-unstyled users-list m-0 avatar-group d-flex align-items-center" style="padding-left: 43%;padding-right: 43%;">
                                    <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" class="avatar avatar-xs pull-up" title="" data-bs-original-title="<?= $usuario['nome'] ?>">
                                        <img src="storage/users/<?= $usuario['imagem'] ?>" alt="Avatar" class="rounded-circle">
                                    </li>
                                </ul>
                            </td>
                            <td><?= $usuario['nome'] ?></td>
                            <td><span class="badge bg-label-primary me-1"><?= $usuario['usuario'] ?></span></td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                        <i class="bx bx-dots-vertical-rounded"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="/showuser?id=<?= $usuario['id'] ?>"><i class="bx bx-edit-alt me-1"></i> Editar</a>
                                        <a class="dropdown-item" href="/deleteuser?id=<?= $usuario['id'] ?>"><i class="bx bx-trash me-1"></i> Deletar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                <?php } ?>
            </table>
        </div>
    </div>
</div>