<!DOCTYPE html>

<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Art Corpus | Gerenciamento de Conteúdo</title>


    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="assets/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="assets/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="assets/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="assets/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="assets/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->

    <!-- Helpers -->
    <script src="assets/assets/vendor/js/helpers.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="assets/assets/js/config.js"></script>
    <script src="https://kit.fontawesome.com/1e08d5da40.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu" style="background-color: #d3d4d6;">
                <div class="app-brand demo">
                    <a href="/front" class="app-brand-link">
                        <img src="images/logo.png" style="width: 80%;">
                    </a>

                    <a href="/front" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                    <!-- Inicio -->
                    <li class="menu-item">
                        <a href="/front" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            <div data-i18n="Analytics">Início</div>
                        </a>
                    </li>

                    <!-- Layouts -->

                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">MENU</span>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link menu-toggle">
                            <i class='menu-icon tf-icons bx bx-book'></i>
                            <div data-i18n="slide">Slides</div>
                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a href="/showslide" class="menu-link">
                                    <div data-i18n="showslide">Ver Slides</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="/createslide" class="menu-link">
                                    <div data-i18n="createslide">Adicionar Slide</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link menu-toggle">
                            <i class='menu-icon tf-icons bx bx-book'></i>
                            <div data-i18n="service">Serviços</div>
                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a href="/listservices" class="menu-link">
                                    <div data-i18n="listservices">Ver Serviços</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="/createservice" class="menu-link">
                                    <div data-i18n="createservice">Adicionar Serviços</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link menu-toggle">
                            <i class='menu-icon tf-icons bx bx-book'></i>
                            <div data-i18n="users">Usuários</div>
                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a href="/listusers" class="menu-link">
                                    <div data-i18n="listusers">Ver Usuários</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="/createuser" class="menu-link">
                                    <div data-i18n="createuser">Adicionar Usuário</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link menu-toggle">
                            <i class='menu-icon tf-icons bx bx-book'></i>
                            <div data-i18n="contact">Dados de Contato</div>
                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a href="/listdatas" class="menu-link">
                                    <div data-i18n="listdatas">Ver Dados</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Sessão</span>
                    </li>
                    <li class="menu-item">
                        <a href="javascript:void(0);" class="menu-link menu-toggle">
                            <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                            <div data-i18n="session">Sessão do Usuário</div>
                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a href="" class="menu-link" target="_blank" data-bs-toggle="modal" data-bs-target="#alterSenha">
                                    <div data-i18n="Basic">Alterar Senha</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="/logout" class="menu-link" target="_blank">
                                    <div data-i18n="Basic">Encerrar Sessão</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </aside>
            <!-- / Menu -->

            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <div class="navbar-nav align-items-center">
                            <div class="nav-item d-flex align-items-center">
                                <i class="bx bx-search fs-4 lh-0"></i>
                                <input type="text" class="form-control border-0 shadow-none" placeholder="Buscar..." aria-label="Buscar ..." />
                            </div>
                        </div>
                        <!-- /Search -->
                    </div>
                </nav>

                <div class="content-wrapper">


                    <?= $this->content() ?>

                    <!-- Footer -->
                    <section id="component-footer">
                        <footer class="footer bg-light">
                            <div class="container-fluid d-flex flex-md-row flex-column justify-content-between align-items-md-center gap-1 container-p-x py-3">
                                <div>
                                    <a href="#" class="footer-text fw-bolder">Phone Store </a>
                                    © <script>
                                        document.write(new Date().getFullYear());
                                    </script>
                                </div>
                                <div>
                                    <a href="/logout" class="btn btn-sm btn-outline-danger"><i class="bx bx-log-out-circle"></i> Finalizar Sessão</a>
                                </div>
                            </div>
                        </footer>
                    </section>
                    <!-- / Footer -->

                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    <!-- Modal alterar senha -->
    <div class="modal fade" id="alterSenha" tabindex="-1" aria-hidden="true">
        <form action="/updatepassword" method="POST" name="formsenha">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel1">Alterar Senha</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" value="<?= $_SESSION['id'] ?>">
                        <div class="row mb-3">
                            <div class="col md-12">
                                <label for="novaSenha" class="form-label">Nova Senha</label>
                                <input type="password" id="novaSenha" class="form-control" name="novaSenha" placeholder="Digite uma nova senha" required />
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col md-12">
                                <label for="senha" class="form-label">Confirmar Senha</label>
                                <input type="password" id="senha" class="form-control" name="senha" placeholder="Digite a nova senha novamente" required />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                            Cancelar
                        </button>
                        <button type="submit" onclick="return validar()" class="btn btn-success">Salvar </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- Fim modal -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="assets/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="assets/assets/vendor/libs/popper/popper.js"></script>
    <script src="assets/assets/vendor/js/bootstrap.js"></script>
    <script src="assets/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="assets/assets/vendor/js/menu.js"></script>

    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Validar campos senha -->
    <script>
        function validar() {
            let novaSenha = formsenha.novaSenha.value;
            let senha = formsenha.senha.value;

            if (novaSenha === '' || novaSenha <= 6) {
                swal("Atenção!", "A senha precisa ter no minimo 6 caracteres!", "warning");
                formsenha.novaSenha.focus();
                return false;
            } else if (novaSenha != senha || senha <= 6) {
                swal("Atenção!", "A senhas não são iguais!", "warning");
                formsenha.novaSenha.focus();
                return false;
            }
        }


        // let urlParams = new URLSearchParams(window.location.search);
        // let pwdSuccess = urlParams.has('feedback')

        // if(pwdSuccess) {
        //     swal("Sucesso!", "A senhas foi alterada!", "success");
        // }
    </script>
    <!-- Fim validação -->

    <!-- Main JS -->
    <script src="assets/assets/js/main.js"></script>

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>