<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Formulário /</span> Dados de Contato</h4>

    <div class="row">
        <div class="col-xl-12">
            <div class="card mb-4">
                <h5 class="card-header">Dados de Contato</h5>
                <form action="<?= $this->view->contato != '' ? '/setContato?id=' . $this->view->contato['id'] : '/setContato' ?>" method="post">
                    <div class="card-body">
                        <input required type="hidden" name="id" id="id" value="<?= $this->view->contato[''] ?>">
                        <div class="mb-3 row">
                            <label for="cep-text" class="col-md-2 col-form-label">CEP</label>
                            <div class="col-md-10">
                                <input required class="form-control" name="cep" type="text" id="cep" value="<?= $this->view->contato['cep'] ?>" size="10" maxlength="9" onblur="pesquisacep(this.value);" autofocus>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="logradouro" class="col-md-2 col-form-label">Logradouro</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="search" name="logradouro" id="logradouro" readonly>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="complemento" class="col-md-2 col-form-label">Complemento</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" value="<?= $this->view->contato['complemento'] ?>" name="complemento" id="complemento" placeholder="Ex: Ed. Le Parc, Subsolo">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="bairro" class="col-md-2 col-form-label">Bairro</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" name="bairro" id="bairro" readonly>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="numero" class="col-md-2 col-form-label">Número</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" value="<?= $this->view->contato['numero'] ?>" name="numero" id="numero">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="cidade" class="col-md-2 col-form-label">Cidade</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" name="cidade" id="cidade" readonly>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="uf" class="col-md-2 col-form-label">UF</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" value="" name="uf" id="uf" readonly>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="localizacao" class="col-md-2 col-form-label">Localizacao (url)</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" value="<?= $this->view->contato['localizacao'] ?>" name="localizacao" id="localizacao">
                                <small><a href="https://www.google.com.br/maps" target="__blank">Buscar localização</a></small>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="instagram" class="col-md-2 col-form-label">Instagram (url)</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" value="<?= $this->view->contato['instagram'] ?>" name="instagram" id="instagram" placeholder="Ex: https://instagram.com/username">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="whatsapp" class="col-md-2 col-form-label">WhatsApp</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="text" value="<?= $this->view->contato['whatsapp'] ?>" name="whatsapp" id="whatsapp" placeholder="Ex: 11111111111" maxlength="11">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="email" class="col-md-2 col-form-label">E-mail</label>
                            <div class="col-md-10">
                                <input required class="form-control" type="email" value="<?= $this->view->contato['email'] ?>" id="email" name="email">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="sobreempresa" class="col-md-2 col-form-label">Sobre a Empresa</label>
                            <div class="col-md-10">
                                <textarea required id="sobreempresa" class="form-control" name="sobre" style="resize: none;" rows="5" maxlength="1000"><?= $this->view->contato['sobre'] ?></textarea>
                            </div>
                        </div>
                        <div class="row justify-content-end mt-5">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-success">Salvar</button>
                                <a href="/front" class="btn btn-info">Voltar</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function limpa_formulário_cep() {
        //Limpa valores do formulário de cep.
        document.getElementById('logradouro').value = ("");
        document.getElementById('bairro').value = ("");
        document.getElementById('cidade').value = ("");
        document.getElementById('uf').value = ("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('logradouro').value = (conteudo.logradouro);
            document.getElementById('bairro').value = (conteudo.bairro);
            document.getElementById('cidade').value = (conteudo.localidade);
            document.getElementById('uf').value = (conteudo.uf);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }

    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if (validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('logradouro').value = "...";
                document.getElementById('bairro').value = "...";
                document.getElementById('cidade').value = "...";
                document.getElementById('uf').value = "...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = 'https://viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };
</script>