<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Slide /</span> Apresentação de Slides</h4>

    <div class="row">
        <?php if (empty($this->view->dados)): ?>
            <div class="container text-center" style="padding-top: 20%;padding-bottom: 20%;">
                <h3>Sem imagens cadastradas</h3>
            </div>
        <?php endif; ?>
        <?php foreach ($this->view->dados as $key => $slide) { ?>
            <div class="col-md-6 col-lg-4 mb-3">
                <div class="card h-100">
                    <img class="card-img-top" src="storage/slides/<?= $slide['imagem'] ?>" alt="Card image cap">
                    <small style="margin-left: 1%;"><?= 'Imagem '. 1 + $key ?></small>
                    <div class="card-body">
                        <h5 class="card-title">Título: <strong><?= $slide['titulo'] ?></strong></h5>
                        <p class="card-text">
                            Legenda: <?= $slide['descricao'] ?>    
                        </p>
                        <a href="/showslide?id=<?= $slide['id'] ?>" class="btn btn-info">Editar</a>
                        <a href="/deleteslide?id=<?= $slide['id'] ?>" class="btn btn-danger">Deletar</a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>