<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Formulário /</span> Edição de Slides</h4>
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Dados do Slide</h5>
                    <small class="float-end" style="color: red;">Todos os campos são obrigatórios</small>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" action="/updateslide?id=<?= $_GET['id'] ?>">
                        <div class="mb-3">
                            <label class="form-label" for="imagem">Imagem</label>
                            <input type="file" class="form-control" id="imagem" name="imagem">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="titulo">Título</label>
                            <input type="text" class="form-control" id="titulo" value="<?= $this->view->dados['titulo'] ?>" name="titulo" required>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="legenda">Legenda</label>
                            <input type="text" id="legenda" class="form-control" value="<?= $this->view->dados['descricao'] ?>" name="descricao" required>
                        </div>
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>