<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Lista /</span> Todas as Dúvidas</h4>
    <h5 class="mt-4">Dúvidas</h5>
    <div class="row">
        <div class="col-md mb-4 mb-md-0">
            <div class="accordion mt-3" id="accordionExample">
                <?php foreach ($this->view->dados as $key => $duvida) { ?>
                    <div class="card accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button type="button" class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#<?= 'duvida'.$duvida['id'] ?>" aria-expanded="false" aria-controls="<?= 'duvida'.$duvida['id'] ?>">
                                <?= $duvida['titulo'] ?>
                            </button>
                        </h2>

                        <div id="<?= 'duvida'.$duvida['id'] ?>" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <strong>Resposta:</strong> <?= $duvida['duvida'] ?><br>
                                <a href="/showduvida?id=<?= $duvida['id'] ?>" class="btn btn-sm btn-info" style="margin-top: 10px;">Editar</a>  
                                <a href="/deleteduvida?id=<?= $duvida['id'] ?>" class="btn btn-sm btn-danger" style="margin-top: 10px;">Deletar</a>  
                            </div>
                        </div>
                    </div>
                <?php } ?> 
            </div>
        </div>
    </div>
</div>